### ISSUE TITLE
Meetup 2/28 Bug List

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#2169]
- [x] Fader box does not cover all of FoV https://github.com/mozilla/hubs/issues/2120
- [ ] Changing scene twice when tabbed away fails due to double fade #2337
- [ ] Issue with waypoints when joining room
- [ ] Exiting immersive mode perf https://github.com/mozilla/hubs/issues/2168

**Comment by johnshaughnessy** [comment]
I think what was happening with the waypoints is that they were marked with "snapToNavMesh", but the snap was not happening until the user actually tried to move. If instead they were not marked with "snapToNavMesh", then what is supposed to happen is that the user spawns with their head/camera where the spawn point transform is, and they are put in fly mode with "land when you fly close to the floor" turned on.

**Comment by gfodor** [comment]
ah ok so this is not a bug?

**Comment by johnshaughnessy** [comment]
It is a bug -- the snap to the nav mesh should happen immediately; should not have to wait until the user tries to move

**Comment by gfodor** [comment]
oh understood thanks for clarifying

**Comment by netpro2k** [comment]
Individual issues have been filed for the things mentioned in here, so closing this meta-issue.

**Comment by johnshaughnessy** [comment]
> Issue with waypoints when joining room

This issue ended up being that there was only 1 spawn point, and it was marked "occupiable", so everyone (except the one lucky person who occupied it successfully) spawned at the origin of the space.

Scene url https://hubs.mozilla.com/yzMxcJT/shy-beloved-walkabout

Creating an issue to improve the instructions for how to use waypoints / spawn points because I've seen several people get burned by this when creating their scenes.
