### ISSUE TITLE
Revamp Audio Preferences & System

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2305]
This is a list of the different audio system changes that we hope to make that are likely related to one another and should be viewed as a cohesive system.

- [ ] Implement Push to Talk as a user-configurable setting: https://github.com/mozilla/hubs/issues/1952
- [ ] Add some kind of audio affordance in the user list to indicate volume: #1381
- [ ] Boost or de-positionalize audio after holding cursor over an avatar: #1393
- [ ] Audio/Video comes in too loudly and volume settings don't carry over after refresh: #1492
- [ ] Separate user preference audio slider for background audio in the scene: #2143
- [ ] Improve audio behaviors for rooms and individual users: #1853 
- [ ] Improve Audio Device Behavior: #1826
- [ ] Override scene settings with room settings for audio falloff: #2334

**Comment by misslivirose** [comment]
Also of interest: #2322, #2106, general question about whether or not room owners should be able to override scene audio settings (I think @blairmacintyre had some thoughts on that last point - Blair, did you file that already somewhere? My search results are showing up lacking, but I think this is something you mentioned in a call)

**Comment by blairmacintyre** [comment]
I think perhaps https://github.com/mozilla/hubs/issues/2334, which you closed when you copied it over to another issue where you were collecting audio things? :)
