### ISSUE TITLE
Q2 UX / UI "Paper cuts" Improvement List

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2306]
This is a list to track UX / UI issues work that are relatively small, scoped, and ready to fix. 

- [ ]  Add button to return to lobby: #2304 
- [ ]  Room Details Scrollbar: #1484 
- [ ]  Pin Naming Convention: #1475 
- [ ] Button Naming Conventions: #1483
- [ ] Object Loading Screen: #1669
- [ ] Show an indicator if you have fly mode enabled: #1693
- [ ] Improve Broken Media Link Appearance: #1747
- [ ] Unclear icon in object menu: #1784
- [ ] Avoid using same icon for two different behaviors: #1802
- [ ] Prompt before changing rooms or reduce distance where the link can be triggered: #1850
- [ ] Hide Inspect Mode UI: #2299
