### ISSUE TITLE
Start working on a public backend API

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2629]
### Motivation
We want to enable people to customize their experience with Hubs and Hubs Cloud instances by offering public backend API access for doing common tasks.

I'll use this as a meta-issue to start tracking this goal and we can break it into more/different ones as needed.

Initially, I think we need to: 
- [x] https://github.com/mozilla/hubs/issues/2686 Decide yay/nay on the following tech choices: GraphQL, OAS
- [x] https://github.com/mozilla/hubs/issues/2687 (If we go with GraphQL), figure out authentication/routing and add it to Robert's GraphQL PR started here https://github.com/mozilla/reticulum/pull/388
- [x] https://github.com/mozilla/hubs/issues/2688 (If we go with REST + OAS), see what it takes to write an schema for the room query API started here https://github.com/mozilla/reticulum/pull/382
- [x] https://github.com/mozilla/hubs/issues/2689 Figure out how to offer a standard/uniform API
- [x] https://github.com/mozilla/hubs/issues/2690 Create a loosely prioritized list of user stories we want the public reticulum API to address

### Related Resources
 - User asking "Is there a public API I can use?" https://github.com/mozilla/reticulum/issues/390
 - Change the scene https://github.com/mozilla/hubs/issues/1976
 - Create rooms https://github.com/mozilla/hubs/issues/1976
 - Control who has access to which rooms https://github.com/mozilla/hubs/issues/1976
 - Bulk account creation https://github.com/mozilla/hubs/issues/1976
 - CRUD APIs for Reticulum resources (hubs, scenes, avatars, files, etc)  https://github.com/mozilla/hubs/issues/1976
 - Query room status (e.g. how many people are in the lobby/room) https://github.com/mozilla/hubs/issues/1976
 - Room query API written in our pre-existing pattern https://github.com/mozilla/reticulum/pull/382
 - Exploration of using GraphQL https://github.com/mozilla/reticulum/pull/388
 - Technical Design doc, mostly around which libraries to use (not which user stories to focus on) https://www.notion.so/Reticulum-67e38c3b7f5b46f0979a045ac9b3b764

**Comment by robertlong** [comment]
I'd split these out into separate issues.

**Comment by johnshaughnessy** [comment]
Still TODO:

- [ ] Convert user stories to github issues to include in the next sprint
- [ ] Finish addressing known unknowns in https://github.com/mozilla/hubs/issues/2689

**Comment by johnshaughnessy** [comment]
Closing this and will track progress with newly created issues that include next steps:
https://github.com/mozilla/hubs/issues/2776
https://github.com/mozilla/hubs/issues/2777
https://github.com/mozilla/hubs/issues/2778
https://github.com/mozilla/hubs/issues/2779
