### ISSUE TITLE
Submit PRs for upstream repos

### ISSUE THREAD

**Issue by netpro2k** [mozilla/hubs#362]
We currently have dev branches of several of our upstream dependancies that we havent even open PRs for upstream. Once PRs are approved we should update package.json to point at the updated versions on NPM.

PRs  that need submitting for `aframe-extras`  (@robertlong)
- [x] Precompute Navmesh
- [ ] Update hubs client once PRs have landed

PRs that need submitting for  `aframe-input-mapping-component` (@johnshaughnessy):
- [x] Multiple bindings per button 
- [x] Behaviour fixes
- [ ] Update hubs client once PRs have landed

PRs that need submitting for `aframe-teleport-controls`:
- [x] Incremental teleport line (@johnshaughnessy)
- [ ] Pause support (no longer being used) (@netpro2k)
- [x] Fix landing normal (@robertlong)
- [ ] Update hubs client once PRs have landed

PRs that need submitting for `aframe-xr` (@brianpeiris):
- [ ] Pose fix
- [ ] Update hubs client once PRs have landed

PRs that need submitting for  `networked-aframe`:
- [ ] Aframe compatability fixes (@robertlong)
- [ ] lerping fixes (@robertlong)
- [ ] remove entity fixes (@johnshaughnessy)
- [ ] safari audio fixes (@brianpeiris)
- [ ] return a value from conenct (@netpro2k)
- [ ] Update hubs client once PRs have landed

PRs that need submitting for  `nipplejs` (@johnshaughnessy) :
- [x] Handle `pointercancel`
- [ ] Update hubs client once PRs have landed

PRs that need submitting for `super-hands` (@InfiniteLee):
- [x] Stretchable using world space
- [x] Programmatic grabbing
- [ ] Update hubs client once PRs have landed

**Comment by misslivirose** [comment]
Going to resolve this given the age of the bug - if we need to re-open specific tasks, let's give them new issues.
