### ISSUE TITLE
content/scene UX update checklist

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#891]
- [x] recenter and restyle chatbox
- [x] show chatbox on mobile, move joysticks to landscape
- [x] move photo button into chatbox
- [x] change send button in chatboxes

- [x] add settings menu
- [x] add change scene to settings menu (and hide w/o permissions)
- [x] add help to settings menu
- [x] add rename room to settings menu (and hide w/o permissions)
- [x] add room info to settings menu

- [ ] update room creation flow to have default scene
- [x] add one-time tooltip for scene setting

- [x] move spawn button into HUD on desktop
- [x] move spawn button into HUD on mobile and pop out of immersive mode or show tooltip on desktop VR

- [x] add hotkeys for content browser
- [x] fix up autoselect, 'i'm feeling lucky', highlight-on-click for content browser
- [x] ESC to close search, slash to open
- [x] scene tiles should be links

- [x] add one-time tooltip for pause menu on desktop
- [x] add one-time tooltip for pause menu on mobile
- [x] add one-time tooltip for locomotion on desktop
- [x] add one-time tooltip for locomotion on mobile

- [x] add support for spawning scene links

**Comment by gfodor** [comment]
last one gated on scene library

**Comment by gfodor** [comment]
this is basically on track, closing
